// Mocks generated by Mockito 5.4.6 from annotations
// in miniweather/test/infrastructure/repositories/weather_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:miniweather/domain/datasources/weather_datasource.dart' as _i3;
import 'package:miniweather/domain/entities/location.dart' as _i5;
import 'package:miniweather/domain/entities/weather_data.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeWeatherData_0 extends _i1.SmartFake implements _i2.WeatherData {
  _FakeWeatherData_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [WeatherDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherDatasource extends _i1.Mock implements _i3.WeatherDatasource {
  MockWeatherDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.WeatherData> getWeatherData(_i5.Location? location) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWeatherData,
          [location],
        ),
        returnValue: _i4.Future<_i2.WeatherData>.value(_FakeWeatherData_0(
          this,
          Invocation.method(
            #getWeatherData,
            [location],
          ),
        )),
      ) as _i4.Future<_i2.WeatherData>);
}
