// Mocks generated by Mockito 5.4.6 from annotations
// in miniweather/test/presentation/providers/weather_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:connectivity_plus/connectivity_plus.dart' as _i10;
import 'package:connectivity_plus_platform_interface/connectivity_plus_platform_interface.dart'
    as _i11;
import 'package:geolocator/geolocator.dart' as _i3;
import 'package:miniweather/config/constants/temp_unit.dart' as _i9;
import 'package:miniweather/domain/entities/location.dart' as _i6;
import 'package:miniweather/domain/entities/weather_data.dart' as _i2;
import 'package:miniweather/domain/repositories/local_storage_repository.dart'
    as _i8;
import 'package:miniweather/domain/repositories/weather_repository.dart' as _i4;
import 'package:miniweather/domain/services/geolocation_service.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeWeatherData_0 extends _i1.SmartFake implements _i2.WeatherData {
  _FakeWeatherData_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePosition_1 extends _i1.SmartFake implements _i3.Position {
  _FakePosition_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [WeatherRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherRepository extends _i1.Mock implements _i4.WeatherRepository {
  MockWeatherRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.WeatherData> getWeatherData(_i6.Location? location) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWeatherData,
          [location],
        ),
        returnValue: _i5.Future<_i2.WeatherData>.value(_FakeWeatherData_0(
          this,
          Invocation.method(
            #getWeatherData,
            [location],
          ),
        )),
      ) as _i5.Future<_i2.WeatherData>);
}

/// A class which mocks [GeolocationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockGeolocationService extends _i1.Mock
    implements _i7.GeolocationService {
  MockGeolocationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.Position> getCurrentPosition() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentPosition,
          [],
        ),
        returnValue: _i5.Future<_i3.Position>.value(_FakePosition_1(
          this,
          Invocation.method(
            #getCurrentPosition,
            [],
          ),
        )),
      ) as _i5.Future<_i3.Position>);

  @override
  _i5.Future<String?> getCurrentCity(_i3.Position? position) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentCity,
          [position],
        ),
        returnValue: _i5.Future<String?>.value(),
      ) as _i5.Future<String?>);
}

/// A class which mocks [LocalStorageRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalStorageRepository extends _i1.Mock
    implements _i8.LocalStorageRepository {
  MockLocalStorageRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> saveWeatherData(_i2.WeatherData? weatherData) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveWeatherData,
          [weatherData],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i2.WeatherData?> loadWeatherData() => (super.noSuchMethod(
        Invocation.method(
          #loadWeatherData,
          [],
        ),
        returnValue: _i5.Future<_i2.WeatherData?>.value(),
      ) as _i5.Future<_i2.WeatherData?>);

  @override
  _i5.Future<void> saveTempUnit(_i9.TempUnit? tempUnit) => (super.noSuchMethod(
        Invocation.method(
          #saveTempUnit,
          [tempUnit],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i9.TempUnit?> loadTempUnit() => (super.noSuchMethod(
        Invocation.method(
          #loadTempUnit,
          [],
        ),
        returnValue: _i5.Future<_i9.TempUnit?>.value(),
      ) as _i5.Future<_i9.TempUnit?>);

  @override
  _i5.Future<void> saveLocation(_i6.Location? location) => (super.noSuchMethod(
        Invocation.method(
          #saveLocation,
          [location],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i6.Location?> loadLocation() => (super.noSuchMethod(
        Invocation.method(
          #loadLocation,
          [],
        ),
        returnValue: _i5.Future<_i6.Location?>.value(),
      ) as _i5.Future<_i6.Location?>);
}

/// A class which mocks [Connectivity].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivity extends _i1.Mock implements _i10.Connectivity {
  MockConnectivity() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<List<_i11.ConnectivityResult>> get onConnectivityChanged =>
      (super.noSuchMethod(
        Invocation.getter(#onConnectivityChanged),
        returnValue: _i5.Stream<List<_i11.ConnectivityResult>>.empty(),
      ) as _i5.Stream<List<_i11.ConnectivityResult>>);

  @override
  _i5.Future<List<_i11.ConnectivityResult>> checkConnectivity() =>
      (super.noSuchMethod(
        Invocation.method(
          #checkConnectivity,
          [],
        ),
        returnValue: _i5.Future<List<_i11.ConnectivityResult>>.value(
            <_i11.ConnectivityResult>[]),
      ) as _i5.Future<List<_i11.ConnectivityResult>>);
}
